"""Render GitHub-readable reference pages from the public function docstrings."""

import argparse
import html
import inspect
import json
import re
from pathlib import Path

import meliora

ROOT = Path(__file__).resolve().parents[1]


def prose(text):
    """Escape plain docstring prose for Markdown without changing its content."""
    return re.sub(r"([\\`*_])", r"\\\1", html.escape(text.strip(), quote=False))


def fields(text):
    """Render NumPy-style parameter, return or exception fields as Markdown."""
    result = []
    for line in text.strip().splitlines():
        if not line.strip():
            continue
        if line.startswith(" "):
            result.append(prose(line))
        else:
            name, separator, kind = line.partition(" : ")
            label = f"**`{name}`**"
            if separator:
                label += f" ({prose(kind)})"
            result.append(f"\n{label}\n")
    return "\n".join(result).strip()


def render_method(entry):
    """Return the complete reference for a catalogue entry using its live API."""
    name = entry["name"]
    function = getattr(meliora, name)
    parts = re.split(r"^([A-Za-z ]+)\n-+\n", inspect.getdoc(function), flags=re.MULTILINE)
    sections = dict(zip(parts[1::2], parts[2::2], strict=True))
    reference_links = "\n".join(
        f"- [Statistical reference {i}]({url})"
        for i, url in enumerate(sections["References"].split(), start=1)
    )
    return f"""<!-- Generated by scripts/render_reference.py; edit the function docstring or catalogue. -->
# {entry["title"]}

{prose(parts[0])}

```python
meliora.{name}{inspect.signature(function)}
```

## Parameters

{fields(sections["Parameters"])}

## Returns

{fields(sections["Returns"])}

## Formula, assumptions and interpretation

{prose(sections["Notes"])}

## Example

```{{doctest}}
{sections["Examples"].strip()}
```

{prose(entry["interpretation"])}

## Exceptions

{fields(sections["Raises"])}

## References

{reference_links}
"""


def render_index(catalogue):
    """Return the documentation landing page and grouped method directory."""
    intro = """<!-- Generated by scripts/render_reference.py. -->
# Meliora documentation

Start with the [usage guide](source/usage.md) or the
[Jupyter notebook](../examples/examples.ipynb). The reference below explains each
method's arguments, outputs, formula, assumptions and worked example. Every page
can be read directly on GitHub.

## Method reference
"""
    groups = []
    for family in dict.fromkeys(entry["family"] for entry in catalogue):
        links = [
            f"- [{entry['title']}](source/meliora/{entry['name']}.md)"
            for entry in catalogue
            if entry["family"] == family
        ]
        groups.append(f"### {family}\n\n" + "\n".join(links))
    return (
        intro
        + "\n"
        + "\n\n".join(groups)
        + """

## Validation and maintenance

- [Method checklist](method_checklist.md): the eight acceptance criteria and evidence for every method.
- [Validation guide](source/validation.md): commands to reproduce tests, examples and documentation checks.
- [Contribution guide](source/contributing.md): how to update methods and their documentation.

`method_catalog.json` connects each method to its parameters, notebook example and
regression test. The Markdown reference pages are generated from the function
docstrings; CI checks that the committed pages remain current.

`source/conf.py` and `source/index.rst` configure the Sphinx documentation build.
They produce HTML documentation and run the reference examples. Generated HTML
belongs in the ignored `_build/` folder and is not committed.
"""
    )


def check_reference(catalogue):
    """Fail if a reference page or the documentation directory is stale."""
    expected = {ROOT / "docs/source/meliora" / f"{entry['name']}.md" for entry in catalogue}
    actual = set((ROOT / "docs/source/meliora").glob("*.*"))
    assert actual == expected, "Reference directory contains missing or obsolete pages"
    pages = {ROOT / "docs/README.md": render_index(catalogue)}
    pages.update(
        {ROOT / "docs/source/meliora" / f"{entry['name']}.md": render_method(entry) for entry in catalogue}
    )
    for path, content in pages.items():
        assert path.read_text(encoding="utf-8") == content, (
            f"Stale documentation: {path.relative_to(ROOT)}; run python scripts/render_reference.py"
        )


def main():
    """Write reference pages, or check them without changing files."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if committed reference pages are stale")
    args = parser.parse_args()
    catalogue = json.loads((ROOT / "docs/method_catalog.json").read_text(encoding="utf-8"))
    if not args.check:
        for entry in catalogue:
            path = ROOT / "docs/source/meliora" / f"{entry['name']}.md"
            path.write_text(render_method(entry), encoding="utf-8", newline="\n")
        (ROOT / "docs/README.md").write_text(render_index(catalogue), encoding="utf-8", newline="\n")
    check_reference(catalogue)
    print(f"{len(catalogue)} complete Markdown references and the documentation index match the public API")


if __name__ == "__main__":
    main()
